Library/Lib.Web/Controllers/Books/BooksController.cs
using Lib.Services;
using Lib.Services.Core;
using Lib.Services.Dtos;
using Lib.Services.Paging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;

namespace Lib.Web.Controllers.Books
{
    public class BooksController : BaseController
    {
        private readonly IBooksServices _bookSerivce;
        private readonly IGenersServices _genersServices;

        public BooksController(IBooksServices bookSerivce, IGenersServices genersServices)
        {
            _bookSerivce = bookSerivce;
            _genersServices = genersServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("GetBook/{id?}")]
        public IActionResult GetBook(Guid? id)
        {
           
            var result = _bookSerivce.GetBook(id ?? Guid.Empty);
            if (result.IsSuccess)
            {
                _bookSerivce.Commit();
                AddUpdateBooksDto addDto = _mapper.Map<AddUpdateBooksDto, BooksDto>(result.Data);
                addDto = addDto ?? new AddUpdateBooksDto();
               
                var gener = _genersServices.GetGeneres();
                if (!gener.IsSuccess)
                    return StatusCode(StatusCodes.Status500InternalServerError, gener);

                addDto.Geners = gener.Data;
                return PartialView("_AddUpdate", addDto);
            }
            else { return BadRequest(result); }
        }

        [HttpGet]
        [Route("GetDetailBook/{id}")]
        public IActionResult GetDetailBook(Guid id)
        {
            var result = _bookSerivce.GetBook(id);
            if (result.IsSuccess)
            {
                return PartialView("_Detail", result.Data);
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }


        }

        [HttpPost]
        [Route("AddBook")]
        [ValidateAntiForgeryToken]
        public IActionResult AddBook(AddUpdateBooksDto reqDto)
        {
            if (!ModelState.IsValid)
                return StatusCode(StatusCodes.Status500InternalServerError);

            var result = _bookSerivce.AddUpdateBook(reqDto);
            if (result.IsSuccess)
            {
                _bookSerivce.Commit();
                return Ok(true);
            }
            else
            {
                _bookSerivce.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }


        }

        [HttpDelete]
        [Route("DeleteBook/{id}")]
        public IActionResult DeleteBook(Guid id)
        {
            var result = _bookSerivce.DeleteBook(id);
            if (result.IsSuccess)
            {
                _bookSerivce.Commit();
                return Ok(true);
            }
            else
            {
                _bookSerivce.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }

        }

        [HttpPost]
        [Route("GetBookPaging")]
        public IActionResult GetBookPaging([FromForm] DataTableRequest request)
        {
            var result = _bookSerivce.BookPaging(request);
            if (result.IsSuccess)
            {
                return Ok(new
                {
                    draw = request.draw,
                    recordsFiltered = result.Data.TotalRecords,
                    recordsTotal = result.Data.TotalRecords,
                    data = result.Data.Items
                });
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }
        }

        [HttpGet]
        [Route("BooksLoan")]
        public IActionResult BooksLoan()
        {
            return View();
        }

        [HttpGet]
        [Route("GetBooksLoan/{id_author_title?}")]
        public IActionResult GetBooksLoan(string? id_author_title)
        {
            var result = _bookSerivce.GetLoanBook(id_author_title);
            if (result.IsSuccess)
            {
                return PartialView("_BooksLoan", result.Data);
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }


        }
    }
}

Library/Lib.Web/Controllers/Dashboard/DashboardController.cs
using Lib.Services.Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Lib.Web.Controllers.Dashboard
{
    public class DashboardController : BaseController
    {
        public DashboardController() 
        {

        }
        public IActionResult Index()
        {
            return View();
        }

       
    }
}

Library/Lib.Web/Controllers/Genere/GenereController.cs
using Lib.Services;
using Lib.Services.Core;
using Lib.Services.Dtos;
using Lib.Services.Paging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace Lib.Web.Controllers.Genere
{
    public class GenereController : BaseController
    {
        private readonly IGenersServices _genersServices;

        public GenereController(IGenersServices genersServices)
        {
            _genersServices = genersServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("GetGenere/{id?}")]
        public IActionResult GetGenere(int? id)
        {
            var result = _genersServices.GetGenere(id ?? 0);
            if (result.IsSuccess)
            {
                AddUpdateGenersDto addDto = _mapper.Map<AddUpdateGenersDto, GenersDto>(result.Data);
                return PartialView("_AddUpdate", addDto);
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }
        }

        [HttpGet]
        [Route("GetDetailGenere/{id}")]
        public IActionResult GetDetailGenere(int id)
        {
            var result = _genersServices.GetGenere(id);
            if (result.IsSuccess)
            {
                return PartialView("_Detail", result.Data);
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }
        }

        [HttpPost]
        [Route("AddGenere")]
        [ValidateAntiForgeryToken]
        public IActionResult AddGenere(AddUpdateGenersDto reqDto)
        {
            if (!ModelState.IsValid)
                return StatusCode(StatusCodes.Status500InternalServerError);

            var result = _genersServices.AddUpdateGenere(reqDto);
            if (result.IsSuccess)
            {
                _genersServices.Commit();
                return Ok(true);
            }
            else
            {
                _genersServices.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }

        }

        [HttpDelete]
        [Route("DeleteGenere/{id}")]
        public IActionResult DeleteGenere(int id)
        {
            var result = _genersServices.DeleteGenere(id);
            if (result.IsSuccess)
            {
                _genersServices.Commit();
                return Ok(true);
            }
            else
            {
                _genersServices.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }

        }

        [HttpPost]
        [Route("GetGenerePaging")]
        public IActionResult GetGenerePaging([FromForm] DataTableRequest request)
        {
            var result = _genersServices.GenerePaging(request);
            if (result.IsSuccess)
            {
                return Ok(new
                {
                    draw = request.draw,
                    recordsFiltered = result.Data.TotalRecords,
                    recordsTotal = result.Data.TotalRecords,
                    data = result.Data.Items
                });
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }
        }
    }
}

Library/Lib.Web/Controllers/Subscribers/SubscribersController.cs
using Lib.Services;
using Lib.Services.Core;
using Lib.Services.Dtos;
using Lib.Services.Paging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Linq;

namespace Lib.Web.Controllers.Subscribers
{
    public class SubscribersController : BaseController
    {
        private readonly ISubscribersServices _subscribersServices;
        private readonly IBooksServices _booksServices;

        public SubscribersController(ISubscribersServices subscribersServices, IBooksServices booksServices)
        {
            _subscribersServices = subscribersServices;
            _booksServices = booksServices;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("GetSubscriber/{id?}")]
        public IActionResult GetSubscriber(Guid? id)
        {
            var result = _subscribersServices.GetSubscribers(id ?? Guid.Empty);
            if (result.IsSuccess)
            {
                _subscribersServices.Commit();
                AddUpdateSubscribersDto addDto = _mapper.Map<AddUpdateSubscribersDto, SubscribersDto>(result.Data);
                addDto = addDto ?? new AddUpdateSubscribersDto();

                var bookRes = _booksServices.GetAllBooks();
                if (!bookRes.IsSuccess)
                    return BadRequest(result);

                var selectedbookRes = _booksServices.SubscriberBooks(id ?? Guid.Empty);
                if (!selectedbookRes.IsSuccess)
                    return BadRequest(selectedbookRes);

                addDto.LoanedBooks = selectedbookRes.Data.Select(s => s.Id.Value);

                addDto.AllBooks = bookRes.Data.Where(s => !addDto.LoanedBooks.Contains(s.Id.Value));
                addDto.SelectedBooks = selectedbookRes.Data;


                return PartialView("_AddUpdate", addDto);
            }
            else { return BadRequest(result); }
        }

        [HttpGet]
        [Route("GetDetailSubscriber/{id}")]
        public IActionResult GetDetailSubscriber(Guid id)
        {
            var result = _subscribersServices.GetSubscribers(id);
            if (result.IsSuccess)
            {
                var loanedBooks = _booksServices.SubscriberBooks(id);
                if (!loanedBooks.IsSuccess)
                    return StatusCode(StatusCodes.Status500InternalServerError, result);

                result.Data.LoanedBooks = loanedBooks.Data.ToList();

                return PartialView("_Detail", result.Data);
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }


        }

        [HttpPost]
        [Route("AddSubscriber")]
        [ValidateAntiForgeryToken]
        public IActionResult AddSubscriber(AddUpdateSubscribersDto reqDto)
        {
            if (!ModelState.IsValid)
                return StatusCode(StatusCodes.Status500InternalServerError);

            var result = _subscribersServices.AddUpdateSubscribers(reqDto);
            if (result.IsSuccess)
            {
                _subscribersServices.Commit();
                return Ok(true);
            }
            else
            {
                _subscribersServices.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }


        }

        [HttpDelete]
        [Route("DeleteSubscriber/{id}")]
        public IActionResult DeleteSubscriber(Guid id)
        {
            var result = _subscribersServices.DeleteSubscribers(id);
            if (result.IsSuccess)
            {
                _subscribersServices.Commit();
                return Ok(true);
            }
            else
            {
                _subscribersServices.Rollback();
                return StatusCode(StatusCodes.Status500InternalServerError, result);
            }

        }

        [HttpPost]
        [Route("GetSubscriberPaging")]
        public IActionResult GetSubscriberPaging([FromForm] DataTableRequest request)
        {
            var result = _subscribersServices.SubscribersPaging(request);
            if (result.IsSuccess)
            {
                return Ok(new
                {
                    draw = request.draw,
                    recordsFiltered = result.Data.TotalRecords,
                    recordsTotal = result.Data.TotalRecords,
                    data = result.Data.Items
                });
            }
            else { return StatusCode(StatusCodes.Status500InternalServerError, result); }
        }
    }
}

Library/Lib.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" class="light-style" dir="ltr" data-theme="theme-default" data-assets-path="../assets/">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>@ViewData["Title"] - Library</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;600;700;900&display=swap" rel="stylesheet">

    <!-- Icons. Uncomment required icon fonts -->
    <link href="~/fonts/boxicons.css" rel="stylesheet" />

    <!-- Core CSS -->
    <link href="~/css/core.css" rel="stylesheet" class="template-customizer-core-css" />
    <link href="~/css/theme-default.css" rel="stylesheet" class="template-customizer-theme-css" />
    <link href="~/lib/sweet-alert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <!-- Vendors CSS -->
    <link href="~/lib/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />


    <!-- Helpers -->
    <script src="~/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/js/config.js"></script>

</head>
<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo">
                    <a href="index.html" class="app-brand-link">
                        <img width="40" src="~/img/logo.png" id="app_logo" alt="Library" />
                        <span class="app-brand-text demo menu-text fw-bolder ms-2">Library</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Dashboard -->
                    <li class="menu-item active">
                        <a href="/" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-book-reader"></i>
                            <div data-i18n="Analytics">Dashboard</div>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a href="@Url.Action("Index","Subscribers")" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-group"></i>
                            <div data-i18n="Analytics">Subscribers</div>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a href="@Url.Action("Index","Genere")" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-book-content"></i>
                            <div data-i18n="Analytics">Genere</div>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a href="@Url.Action("Index","Books")" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-book"></i>
                            <div data-i18n="Analytics">Books</div>
                        </a>
                    </li>


                </ul>
            </aside>

            <!-- Layout container -->
            <div class="layout-page">
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->
                    <div class="container-fluid flex-grow-1 container-p-y">
                        @RenderBody()
                    </div>
                    <!-- Footer -->
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-fluid d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                ©
                                <script>
                                    document.write(new Date().getFullYear());
                                </script>
                            </div>
                           
                        </div>
                    </footer>
                    <!-- / Footer -->

                    <div class="content-backdrop fade"></div>
                </div>
            </div>
        </div>



        <!-- Modal -->
        <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content" id="modelCenterDynamicContent">
                </div>
            </div>
        </div>
        <!-- Modal -->
        <!-- Toast with Placements -->
        <div class="bs-toast toast toast-placement-ex m-2"
             role="alert"
             aria-live="assertive"
             aria-atomic="true"
             data-delay="2000">
            <div class="toast-header">
                <i class="bx bx-bell me-2"></i>
                <div class="me-auto fw-semibold" id="toastTitle">Bootstrap</div>
                <small id="toastTime">1 sec ago</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body" id="toastMessage">Fruitcake chocolate bar tootsie roll gummies gummies jelly beans cake.</div>
        </div>
        <!-- Toast with Placements -->
        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>
    </div>



   

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/popper/popper.js"></script>
    <script src="~/lib/bootstrap.js"></script>
    <script src="~/lib/datatable/js/datatable.min.js"></script>
    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/js/datatables.buttons.min.js"></script>
    <script src="~/lib/sweet-alert2/sweetalert2.all.min.js"></script>

    <script src="~/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/js/main.js"></script>
    <script src="~/js/b4_toast.js"></script>
    <script src="~/js/site.js"></script>
    <!-- Page JS -->
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Library/Lib.Web/Views/Shared/_WebLayout.cshtml
<!DOCTYPE html>
<html lang="en" class="light-style" dir="ltr" data-theme="theme-default" data-assets-path="../assets/">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>@ViewData["Title"] - Library</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;600;700;900&display=swap" rel="stylesheet">

    <!-- Icons. Uncomment required icon fonts -->
    <link href="~/fonts/boxicons.css" rel="stylesheet" />

    <!-- Core CSS -->
    <link href="~/css/core.css" rel="stylesheet" class="template-customizer-core-css" />
    <link href="~/css/theme-default.css" rel="stylesheet" class="template-customizer-theme-css" />
    <link href="~/lib/sweet-alert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/responsive.datatables.min.css" rel="stylesheet" />
    <link href="~/css/newtheme.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <!-- Vendors CSS -->
    <link href="~/lib/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />


    <!-- Helpers -->
    <script src="~/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/js/config.js"></script>
    @RenderSection("Style", required: false)
</head>
<body class="blue_bg">
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar layout-without-menu">
        <div class="layout-container">
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar box-layout box-layout-home"
                     id="layout-navbar">
                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <div class="navbar-nav align-items-center">
                            <ul class="navbar-nav flex-row align-items-center ms-auto" id="navigationlinks">
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("Index","Dashboard")">
                                        <i class='bx bxs-home me-2'></i>
                                        <span class="align-middle">Home </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("Index","Subscribers")">
                                        <i class='bx bxs-book-reader me-2'></i>
                                        <span class="align-middle">Subscribers </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("Index","Books")">
                                        <i class='bx bx-book-add me-2'></i>
                                        <span class="align-middle">Add Books</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("Index","Genere")">
                                        <i class='bx bx-book-add me-2'></i>
                                        <span class="align-middle">Add Gener</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("BooksLoan","Books")">
                                        <i class='bx bx-book-bookmark me-2'></i>
                                        <span class="align-middle">Loan/Books</span>
                                    </a>
                                </li>



                            </ul>

                        </div>

                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">
                        <!-- Layout Demo -->
                        @RenderBody()
                        <!--/ Layout Demo -->
                    </div>
                    <!-- / Content -->
                    <!-- Footer -->
                    <footer class="content-footer footer bg-footer-theme">
                        <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                            <div class="mb-2 mb-md-0">
                                © <script>document.write(new Date().getFullYear());</script>
                            </div>

                        </div>
                    </footer>
                    <!-- / Footer -->
                    <!-- Modal -->
                    <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content" id="modelCenterDynamicContent">
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                    <!-- Toast with Placements -->
                    <div class="bs-toast toast toast-placement-ex m-2"
                         role="alert"
                         aria-live="assertive"
                         aria-atomic="true"
                         data-delay="2000">
                        <div class="toast-header">
                            <i class="bx bx-bell me-2"></i>
                            <div class="me-auto fw-semibold" id="toastTitle">Bootstrap</div>
                            <small id="toastTime">1 sec ago</small>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body" id="toastMessage">Fruitcake chocolate bar tootsie roll gummies gummies jelly beans cake.</div>
                    </div>
                    <!-- Toast with Placements -->
                    <!-- Overlay -->
                    <div class="layout-overlay layout-menu-toggle"></div>
                    <div class="content-backdrop fade"></div>
                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>
    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/popper/popper.js"></script>
    <script src="~/lib/bootstrap.js"></script>

    <script src="~/lib/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables/js/datatables.bootstrap4.min.js"></script>
    <script src="~/lib/datatables/js/datatables.buttons.min.js"></script>
    <script src="~/lib/datatable/js/datatable.min.js"></script>
    <script src="~/lib/datatables/js/datatables.rowreorder.min.js"></script>
    <script src="~/lib/datatables/js/datatables.responsive.min.js"></script>
    <script src="~/lib/sweet-alert2/sweetalert2.all.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/js/main.js"></script>
    <script src="~/js/b4_toast.js"></script>
    <script src="~/js/site.js"></script>
    <!-- Page JS -->
    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

    <script>
        $(document).ready(function () {
            const current = window.location.href;
            document.querySelectorAll("#navigationlinks a").forEach(function (elm) {
                elem = elm.parentElement;
                //elem.classList.add("btn-outline-secondary");
                if (elm.href == (current)) {
                    elem.classList.add("active");
                }
                else {
                    elem.classList.remove("active");
                }

            });

            formValiderRefresh($('form')[0])

        })
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>